### ISSUE TITLE
Invalid argument for foreach()

### ISSUE THREAD

**Issue by gndzro** [romaricdrigon/EasyGallery#2]
Right clicking view source after EasyGallery web page loads shows this in the code
`<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/srv/disk5/123456/www/homepage.com/EasyGallery-master/index.php</b> on line <b>46</b><br />`

Looking at line 46 in index.php
`foreach ($list['picture'] as $pic) {`

Solution, add array
`foreach ((array) $list['picture'] as $pic) {`

Web page doesn't seem to be affected after it loads, it just shows error.  I just mention for the sake of maintaining error-free-coding.

**Comment by romaricdrigon** [comment]
Hello ridz16,

Thank you for the note.
Could you please try another fix? Instead of casting to an array, in `lister.php`, replace line 34 `$content = array();` by `$content = array('folder' => [], 'picture' => []);`.
It will prevent another issue. If the fix works for you, I will commit it to main repo.

**Comment by gndzro** [comment]
I updated the code and everything is working fine.  Thanks!
